name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main  # execute when pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.GURITOGURA }}
          aws-secret-access-key: ${{ secrets.GURITOGURATOOKYAKUSAMA }}
          aws-region: eu-west-1

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation create-stack \
            --template-body file://vpc-1.yml \
            --stack-name StackOfGlenn \
            --capabilities CAPABILITY_NAMED_IAM 
